### ISSUE TITLE
Passing number with unit to bp mixin returns invalid CSS

### ISSUE THREAD

**Issue by lachlanmcdonald** [DeloitteDigitalAPAC/DDBreakpoints#10]
Passing a number to the `bp()` mixin with a unit, i.e. `@include bp(900px)` returns invalid CSS:

``` css
@media only screen and (min-width: 56.25pxem) {
    ...
}
```

It boils down to the `bp-add-em()` mixin:

``` scss
@debug bp-add-em(100); // 100em
@debug bp-add-em(100px); // 100pxem
```

Tested using SASS 3.4.19

**Comment by dkeeghan** [comment]
Resolved by update from @lachlanmcdonald's pull request. The SCSS mixin will fire an error to the console using the `@error` SASS command
