### ISSUE TITLE
Add support for comma separated media queries

### ISSUE THREAD

**Issue by keeganstreet** [DeloitteDigitalAPAC/DDBreakpoints#13]
Sometimes I need the same styles to apply on very small screens, and very large screens where the layout might be divided into multiple columns.

It would be nice if the `bp` mixin could generate a comma separated media query, for example:

``` css
@media (max-width: 479px), (min-width: 1024px) {}
```

The closest way to achieve this currently would be to use `bp(0, xxs)` and `bp(l)`, however the output CSS would result in two media queries and all the styles would be duplicated:

``` css
@media (max-width: 479px) {}
@media (min-width: 1024px) {}
```

**Comment by keeganstreet** [comment]
It would also be nice if we could combine the `max-width` and `min-width` rules with other types of media queries, such as `orientation`.

**Comment by keeganstreet** [comment]
CSS already has a syntax for defining comma separated media queries and combining different types of media queries. So rather than re-inventing the wheel by designing a whole new syntax for passing this into a Sass mixin, we may be better off converting DDBreakpoints into a PostCSS plugin.

Perhaps the interface could look something like this:

CSS: `@media (min-width: 1024px) {}`
Sass (current): `@include bp(l) {}`
PostCSS (proposed): `@media bp(l) {}`

CSS: `@media (max-width: 479px) {}`
Sass (current): `@include bp(0, xxs) {}`
PostCSS (proposed): `@media bp(0, xss) {}`

CSS: `@media (max-width: 479px), (min-width: 1024px) {}`
Sass (current): _Not supported_
PostCSS (proposed): `@media bp(0, xss), bp(l) {}`

CSS: `@media (min-width: 480px) and (orientation: landscape) {}`
Sass (current): `@include bp(xs) { @media (orientation: landscape) {} }`
PostCSS (proposed): `@media bp(xs) and (orientation: landscape) {}`

**Comment by dkeeghan** [comment]
@keeganstreet Sounds like a really good idea. The main reason that this feature isn't in the current iteration is because it just possible in Sass while keeping the syntax extremely simple (which was the main reason for writing DDBreakpoints in the first place). 

We'd need to consider as well how we'd update the JS syntax too, especially where it is currently a string, e.g.

`bp(m, l)` is the same for both JS and CSS and we use `"m,l"` as a string shorthand in JS (for use in data attributes for example), how would we write `@media bp(0, xxs), bp(m)` in the JS shorthand notation? Maybe something like `"0,xxs||m"`? How about non-bp related options like `orientation: landscape`?

**Comment by keeganstreet** [comment]
Good questions @dkeeghan,

One solution would be to change the JavaScript API to accept a media query string in the shorthand format I proposed above, and expand it out to a full standard media query.

For example:

``` js
DD.bp.get('bp(0, xxs)');
// Returns '(max-width: 479px)'

DD.bp.get('bp(xs) and (orientation: landscape)');
// Returns '(min-width: 480px) and (orientation: landscape)'

DD.bp.get('bp(0, xss), bp(l)');
// Returns '(max-width: 479px), (min-width: 1024px)'
```

The advantage of this solution is it is very close to standard media query syntax. We are just replacing the `min-width`, `max-width`, `min-height` and `max-height` expressions with our shorthand `bp`/`bph` syntax. We are leaving the other parts of the media query untouched. And it would allow queries to be copied and pasted between CSS and JS.

But of course it is slightly more verbose than the current version of the plugin, i.e. compare `DD.bp.is('bp(0, xxs)');` with `DD.bp.is('0, xxs');`.

Maybe the shorthand syntax could be simplified to this:

``` js
DD.bp.get('[0, xxs]');
// Returns '(max-width: 479px)'

DD.bp.get('[xs] and (orientation: landscape)');
// Returns '(min-width: 480px) and (orientation: landscape)'

DD.bp.get('[0, xss], [l]');
// Returns '(max-width: 479px), (min-width: 1024px)'
```

The square brackets are to allow the plugin to do a string replacement. Otherwise it would be hard to write a regex to select `(xxl)` without selecting real media query expressions like `(monochrome)`.

Edit: the square bracket syntax is not a good idea. Doesn't conform to CSS syntax and results in CSS lint errors. I will do some research into PostCSS plugins.

**Comment by anthonsmith** [comment]
Hi there,

I believe I should not be on this email thread.

Thank you,
Anthony P. Smith
Software Architect

Deloitte Digital
Office 206-633-1167

anthonsmith@deloitte.com<mailto:joserogers@deloitte.com>
http://deloittedigital.com<http://deloittedigital.com/>

**Comment by OZZlE** [comment]
> ```css
> @media (max-width: 479px), (min-width: 1024px) {}
> ```

But that's not the proper syntax even? The correct syntax is:

    @media (max-width: 479px) and (min-width: 1024px) {}

**Comment by dkeeghan** [comment]
Haven't had too many use cases for this feature, will close and reopen later - I suspect this will be entirely solved with element/container queries.
