### ISSUE TITLE
Javascript library needs to be wrapped in a UMD

### ISSUE THREAD

**Issue by jennasalau** [DeloitteDigitalAPAC/DDBreakpoints#15]
This javascript module has no exports and attaches itself to the window object.

How do you feel about wrapping it in a [Universal Module Definition](https://github.com/umdjs/umd) so it has no restrictions on the way it is consumed.

I'm happy to put in the time for a PR if you are open to this?

Jenna

**Comment by keeganstreet** [comment]
Hi Jenna, I think that sounds like a good idea, to allow this module to be used with Webpack, etc. If there is no module loader present can we still attach the module to the same browser global `DD.bp` for backwards compatibility?

**Comment by jeffdowdle** [comment]
Spoke to Jenna about this, I'm going to take a stab at getting this working :)

**Comment by jeffdowdle** [comment]
#17

**Comment by dkeeghan** [comment]
This is getting updated in #17

**Comment by dkeeghan** [comment]
Updated in release ca89ab0
